# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'soriBase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Alamofire', '~> 5.5'
  pod 'RxSwift', '6.5.0'
  pod 'RxCocoa', '6.5.0'
	pod 'RxAlamofire'
	pod 'SnapKit', '~> 5.0.0'
  pod 'ObjectMapper'
  # Pods for soriBase
  post_install do |pi|
      pi.pods_project.targets.each do |t|
          t.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
          end
      end
  end
end
